# site_name: "MORI Field Survey Report"
# site_url: "https://project-mori.github.io/MORI-fieldsurvey-report/"

# theme:
#   name: material
#   features:
#     - navigation.top
#     - content.code.copy

# plugins:
#   - search
#   - roamlinks      # [[内部リンク]] を自動変換
#   - glightbox      # 画像クリックで拡大

# markdown_extensions:
#   - toc:
#       permalink: true
#   - admonition
#   - attr_list
#   - def_list

# extra:
#   social:
#     - icon: material/github
#       link: https://github.com/Project-MORI/MORI-fieldsurvey-report

#   copyright: 
#     © 2025 Project MORI (JICA–IBAMA). All rights reserved.


site_name: "MORI Field Survey Report"
site_url: "https://project-mori.github.io/MORI-fieldsurvey-report/"

theme:
  name: material
  language: ja
  features:
    - navigation.top
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - toc.integrate

plugins:
  - search
  - roamlinks      # [[内部リンク]]
  - glightbox      # 画像クリックで拡大


markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  # - md_in_html
  - def_list
  # - tables

nav:
  - Home: index.md
  - Surveys:
      - surveys/
  - About: about.md

extra:
  social:
    - icon: material/github
      link: https://github.com/Project-MORI/MORI-fieldsurvey-report

  copyright:
    text: © 2025 Project MORI (JICA/IBAMA). All rights reserved.

