site_name: "MORI Field Survey Report"
site_url: "https://project-mori.github.io/MORI-fieldsurvey-report/"

theme:
  name: material
  features:
    - navigation.top
    - content.code.copy

plugins:
  - search
  - roamlinks      # [[内部リンク]] を自動変換
  - glightbox      # 画像クリックで拡大

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list

extra:
  social:
    - icon: material/github
      link: https://github.com/Project-MORI/MORI-fieldsurvey-report

  copyright: >
    © 2025 Project MORI (JICA–IBAMA). All rights reserved.
